--
-- PostgreSQL database dump
--

\restrict R0OeiUbuitw5sPylJc55cTsVlr1KRZsJb0VhDxctITR3hVb6D5lmYex2MrmqWbI

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg12+1)
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: anime; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anime (
    id bigint NOT NULL,
    genre character varying(100),
    image_url character varying(500),
    rank integer,
    score double precision,
    title character varying(255) NOT NULL,
    year integer
);


ALTER TABLE public.anime OWNER TO admin;

--
-- Name: anime_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.anime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: anime; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (3, 'Action, Adventure, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/1448/154111.jpg', 3, 9.12, '죠죠의 기묘한 모험: 스틸 볼 런', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (4, 'Action, Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg', 4, 9.11, '강철의 연금술사: 브라더후드', 2009);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (5, 'Action, Fantasy', 'https://cdn.myanimelist.net/images/anime/1763/150638.jpg', 5, 9.07, '극장판 체인소 맨: 레제편', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (6, 'Drama, Sci-Fi, Suspense', 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg', 6, 9.07, '슈타인즈 게이트', 2011);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (7, 'Action, Comedy, Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1245/116760.jpg', 7, 9.05, '은혼: 더 파이널', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (8, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/3/72078.jpg', 8, 9.05, '은혼°', 2015);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (9, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1517/100633.jpg', 9, 9.05, '진격의 거인 3기 Part 2', 2019);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (10, 'Action, Adventure, Fantasy', 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg', 10, 9.03, '헌터×헌터 (2011)', 2011);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (11, 'Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1976/142016.jpg', 11, 9.02, '은하영웅전설', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (12, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/4/50361.jpg', 12, 9.02, '은혼''', 2011);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (13, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1452/123686.jpg', 13, 9.02, '은혼'': 연장전', 2012);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (14, 'Action, Adventure, Fantasy', 'https://cdn.myanimelist.net/images/anime/1455/146229.jpg', 14, 9.01, '원피스 팬레터', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (15, 'Action, Adventure, Supernatural', 'https://cdn.myanimelist.net/images/anime/1908/135431.jpg', 15, 8.98, '블리치: 천년혈전편', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (16, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/3/83528.jpg', 16, 8.98, '은혼.', 2017);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (17, 'Comedy, Romance', 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', 17, 8.95, '카구야 님은 고백받고 싶어: 울트라 로맨틱', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (18, 'Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1299/110774.jpg', 18, 8.93, '클라나드: 애프터 스토리', 2008);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (19, 'Drama, Romance, Supernatural', 'https://cdn.myanimelist.net/images/anime/1085/114792.jpg', 19, 8.93, '후르츠 바스켓: 더 파이널', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (20, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 20, 8.93, '은혼', 2006);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (21, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg', 21, 8.93, '목소리의 형태', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (22, 'Award Winning, Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1088/135089.jpg', 22, 8.92, '코드 기아스: 반역의 를르슈 R2', 2008);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (23, 'Drama, Mystery', 'https://cdn.myanimelist.net/images/anime/1025/147458.jpg', 23, 8.91, '약사의 혼잣말 2기', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (24, 'Drama', 'https://cdn.myanimelist.net/images/anime/3/88469.jpg', 24, 8.9, '3월의 라이온 2기', 2017);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (25, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/10/51723.jpg', 25, 8.89, '은혼 극장판: 완결편 - 만물상이여 영원하라', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (26, 'Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/10/18793.jpg', 26, 8.89, '몬스터', 2004);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (27, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1776/96566.jpg', 27, 8.88, '은혼. 백은의 혼편 - 후반전', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (28, 'Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1921/154528.jpg', 28, 8.87, '장송의 프리렌 2기', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (29, 'Comedy, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/6/87322.jpg', 29, 8.86, '오와리모노가타리 2기', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (30, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1279/131078.jpg', 30, 8.86, '진격의 거인: 더 파이널 시즌 - 완결편', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (31, 'Action', 'https://cdn.myanimelist.net/images/anime/1443/111830.jpg', 31, 8.85, '킹덤 3기', 2020);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (32, 'Drama, Mystery', 'https://cdn.myanimelist.net/images/anime/1708/138033.jpg', 32, 8.85, '약사의 혼잣말', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (33, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1379/145452.jpg', 33, 8.83, '진격의 거인 완결편: The Last Attack', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (34, 'Action, Adventure, Drama', 'https://cdn.myanimelist.net/images/anime/1170/124312.jpg', 34, 8.83, '빈란드 사가 2기', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (35, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/1825/110716.jpg', 35, 8.83, '바이올렛 에버가든 극장판', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (36, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/5/87048.jpg', 36, 8.82, '너의 이름은.', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (37, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/12/89603.jpg', 37, 8.81, '은혼. 백은의 혼편', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (38, 'Drama, Sports', 'https://cdn.myanimelist.net/images/anime/3/45028.jpg', 38, 8.8, '내일의 죠 2', 1980);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (39, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1000/110531.jpg', 39, 8.79, '진격의 거인: 더 파이널 시즌', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (41, 'Action, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/1084/112813.jpg', 41, 8.78, '키즈모노가타리 III: 냉혈편', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (42, 'Action, Comedy, Supernatural', 'https://cdn.myanimelist.net/images/anime/1918/96303.jpg', 42, 8.78, '모브 사이코 100 II', 2019);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (43, 'Action, Adventure, Drama', 'https://cdn.myanimelist.net/images/anime/1500/103005.jpg', 43, 8.78, '빈란드 사가', 2019);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (44, 'Sports', 'https://cdn.myanimelist.net/images/anime/7/81992.jpg', 44, 8.77, '하이큐!! 카라스노 고교 VS 시라토리자와 학원 고교', 2016);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (45, 'Adventure, Award Winning, Fantasy', 'https://cdn.myanimelist.net/images/anime/6/79597.jpg', 45, 8.77, '센과 치히로의 행방불명', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (46, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1948/120625.jpg', 46, 8.77, '진격의 거인: 더 파이널 시즌 파트 2', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (47, 'Comedy, Mystery, Romance, Supernatural', 'https://cdn.myanimelist.net/images/anime/1807/121534.jpg', 47, 8.76, '모노가타리 시리즈 세컨드 시즌', 2013);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (48, 'Action, Award Winning, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/4/19644.jpg', 48, 8.75, '카우보이 비밥', 1998);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (49, 'Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1182/149879.jpg', 49, 8.75, '타코피의 원죄', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (50, 'Drama', 'https://cdn.myanimelist.net/images/anime/1791/154233.jpg', 50, 8.74, '이국일기', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (51, 'Comedy', 'https://cdn.myanimelist.net/images/anime/1448/127956.jpg', 51, 8.73, '봇치 더 록!', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (52, 'Drama', 'https://cdn.myanimelist.net/images/anime/1216/142086.jpg', 52, 8.73, '울려라! 유포니엄 3', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (53, 'Action', 'https://cdn.myanimelist.net/images/anime/1566/122794.jpg', 53, 8.73, '킹덤 4기', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (54, 'Action, Adventure, Fantasy', 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg', 54, 8.73, '원피스', 1999);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (55, 'Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1321/117508.jpg', 55, 8.72, '86 -에이티식스- 파트 2', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (56, 'Drama', 'https://cdn.myanimelist.net/images/anime/1749/145922.jpg', 56, 8.72, '지. -지구의 운동에 대하여-', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (57, 'Action', 'https://cdn.myanimelist.net/images/anime/1050/139641.jpg', 57, 8.72, '킹덤 5기', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (58, 'Action, Comedy, Supernatural', 'https://cdn.myanimelist.net/images/anime/1228/125011.jpg', 58, 8.72, '모브 사이코 100 III', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (59, 'Adventure, Mystery, Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/9/68095.jpg', 59, 8.72, '충사 속장 2기', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (60, 'Action', 'https://cdn.myanimelist.net/images/anime/1959/151055.jpg', 60, 8.71, '나의 히어로 아카데미아: 파이널 시즌', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (61, 'Award Winning, Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1032/135088.jpg', 61, 8.71, '코드 기아스: 반역의 를르슈', 2006);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (62, 'Comedy, Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1670/130060.jpg', 62, 8.71, '카구야 님은 고백받고 싶어: 첫 키스는 끝나지 않아', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (63, 'Action, Adventure, Supernatural', 'https://cdn.myanimelist.net/images/anime/1164/138058.jpg', 63, 8.7, '블리치: 천년혈전편 - 결별담', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (64, 'Action, Supernatural', 'https://cdn.myanimelist.net/images/anime/1792/138022.jpg', 64, 8.7, '주술회전 2기', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (65, 'Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/1135/114867.jpg', 65, 8.7, '시광대리인', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (66, 'Drama', 'https://cdn.myanimelist.net/images/anime/1493/124765.jpg', 66, 8.7, '쇼와 겐로쿠 라쿠고 신주: 스케로쿠 부활편', 2017);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (67, 'Award Winning, Sports', 'https://cdn.myanimelist.net/images/anime/1745/129284.jpg', 67, 8.7, '더 퍼스트 슬램덩크', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (68, 'Drama', 'https://cdn.myanimelist.net/images/anime/1979/153329.jpg', 68, 8.7, '[최애의 아이] 3기', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (69, 'Action, Supernatural', 'https://cdn.myanimelist.net/images/anime/1908/120036.jpg', 69, 8.69, '귀멸의 칼날: 유곽편', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (70, 'Action, Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1656/137618.jpg', 70, 8.69, '바람의 검심: 추억편', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (71, 'Fantasy', 'https://cdn.myanimelist.net/images/anime/1726/155542.jpg', 71, 8.69, '뾰족모자의 아틀리에', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (72, 'Drama', 'https://cdn.myanimelist.net/images/anime/1795/95088.jpg', 72, 8.69, '바이올렛 에버가든', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (73, 'Comedy, Romance', 'https://cdn.myanimelist.net/images/anime/1643/138581.jpg', 73, 8.68, '내 마음의 위험한 녀석 2기', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (74, 'Comedy', 'https://cdn.myanimelist.net/images/anime/13/11460.jpg', 74, 8.68, 'GTO', 1999);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (75, 'Adventure, Mystery, Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/13/58533.jpg', 75, 8.68, '충사 속장', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (76, 'Action, Adventure, Supernatural', 'https://cdn.myanimelist.net/images/anime/1595/144074.jpg', 76, 8.67, '블리치: 천년혈전편 - 상극담', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (77, 'Sports', 'https://cdn.myanimelist.net/images/anime/8/56617.jpg', 77, 8.67, '더 파이팅: 뉴 챌린저', 2009);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (78, 'Adventure, Award Winning, Drama, Fantasy, Romance', 'https://cdn.myanimelist.net/images/anime/1470/138723.jpg', 78, 8.67, '하울의 움직이는 성', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (79, 'Action', 'https://cdn.myanimelist.net/images/anime/1282/151476.jpg', 79, 8.67, '킹덤 6기', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (80, 'Action, Adventure, Award Winning, Fantasy', 'https://cdn.myanimelist.net/images/anime/1355/147277.jpg', 80, 8.67, '원령공주', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (81, 'Action', 'https://cdn.myanimelist.net/images/anime/1492/150628.jpg', 81, 8.67, '투 비 히어로 X', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (82, 'Drama, Sports', 'https://cdn.myanimelist.net/images/anime/1120/152280.jpg', 82, 8.67, '우마무스메: 신데렐라 그레이 파트 2', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (83, 'Action, Award Winning, Supernatural', 'https://cdn.myanimelist.net/images/anime/1681/148216.jpg', 83, 8.66, '극장판 귀멸의 칼날: 무한성편 - 아카자 재래', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (84, 'Action, Adventure, Drama, Fantasy, Mystery', 'https://cdn.myanimelist.net/images/anime/1634/116782.jpg', 84, 8.66, '마도조사: 완결편', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (85, 'Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1288/151853.jpg', 85, 8.65, '나소흑전기 2: 우리가 원하는 미래', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (86, 'Adventure, Mystery, Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/2/73862.jpg', 86, 8.65, '충사', 2005);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (87, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1173/92110.jpg', 87, 8.65, '진격의 거인 3기', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (88, 'Comedy, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/1142/146776.jpg', 88, 8.64, '모노가타리 시리즈: 오프 & 몬스터 시즌', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (89, 'Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1405/143284.jpg', 89, 8.64, '4월은 너의 거짓말', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (90, 'Adventure, Award Winning, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/4/5123.jpg', 90, 8.64, '천원돌파 그렌라간', 2007);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (91, 'Action, Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1203/139210.jpg', 91, 8.64, '천관사복 2기', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (92, 'Sports', 'https://cdn.myanimelist.net/images/anime/1427/142210.jpg', 92, 8.64, '우마무스메 프리티 더비: 새 시대의 문', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (93, 'Action, Fantasy', 'https://cdn.myanimelist.net/images/anime/1142/112957.jpg', 93, 8.63, '극장판 페이트 스테이 나이트 [Heaven''s Feel] III. 스프링 송', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (94, 'Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/3/37449.jpg', 94, 8.63, '나츠메 우인장 사', 2012);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (95, 'Award Winning, Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/1981/113348.jpg', 95, 8.63, '오드 택시', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (96, 'Award Winning, Drama, Sports', 'https://cdn.myanimelist.net/images/anime/1586/146565.jpg', 96, 8.63, '핑퐁 디 애니메이션', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (97, 'Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/1897/137108.jpg', 97, 8.63, '시광대리인 2기', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (40, 'Sports', 'https://cdn.myanimelist.net/images/anime/4/86334.jpg', 40, 8.78, '더 파이팅', 2000);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (1, 'Adventure, Award Winning, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg', 1, 9.26, '장송의 프리렌', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (2, 'Drama, Fantasy, Suspense', 'https://cdn.myanimelist.net/images/anime/1446/158539.jpg', 2, 9.13, 'Re:제로부터 시작하는 이세계 생활 4기', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (0, '', 'https://cdn.myanimelist.net/images/anime/1921/135489.jpg', 0, 8.71, 'Idol', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (101, 'Action, Supernatural', 'https://cdn.myanimelist.net/images/anime/1659/154920.jpg', 101, 8.62, '주술회전: 사멸회유 전편', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (102, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/1716/142633.jpg', 102, 8.62, '룩 백', NULL);


--
-- Name: anime_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.anime_id_seq', 102, true);


--
-- Name: anime anime_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anime
    ADD CONSTRAINT anime_pkey PRIMARY KEY (id);


--
-- Name: anime uk54eaowtdrykgn24dd0g93dcy4; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anime
    ADD CONSTRAINT uk54eaowtdrykgn24dd0g93dcy4 UNIQUE (title);


--
-- PostgreSQL database dump complete
--

\unrestrict R0OeiUbuitw5sPylJc55cTsVlr1KRZsJb0VhDxctITR3hVb6D5lmYex2MrmqWbI

