--
-- PostgreSQL database dump
--

\restrict HyQftaH4Ns31BXAoePWiqkVv0T6Ma1AsVNpcsKypXiKJRA5hoJHvr3wENXIxvae

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg12+1)
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: anime; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.anime (
    id bigint NOT NULL,
    genre character varying(100),
    image_url character varying(500),
    rank integer,
    score double precision,
    title character varying(255) NOT NULL,
    year integer
);


ALTER TABLE public.anime OWNER TO admin;

--
-- Name: anime_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.anime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: anime; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (1, 'string', 'string', 0, 0.1, 'string', 0);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (2, 'Adventure, Award Winning, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg', 1, 9.26, 'Sousou no Frieren', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (3, 'Drama, Fantasy, Suspense', 'https://cdn.myanimelist.net/images/anime/1446/158539.jpg', 2, 9.13, 'Re:Zero kara Hajimeru Isekai Seikatsu 4th Season', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (4, 'Action, Adventure, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/1448/154111.jpg', 3, 9.12, 'Steel Ball Run: JoJo no Kimyou na Bouken', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (5, 'Action, Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg', 4, 9.11, 'Fullmetal Alchemist: Brotherhood', 2009);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (6, 'Action, Fantasy', 'https://cdn.myanimelist.net/images/anime/1763/150638.jpg', 5, 9.07, 'Chainsaw Man Movie: Reze-hen', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (7, 'Drama, Sci-Fi, Suspense', 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg', 6, 9.07, 'Steins;Gate', 2011);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (8, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1517/100633.jpg', 9, 9.05, 'Shingeki no Kyojin Season 3 Part 2', 2019);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (9, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/3/72078.jpg', 8, 9.05, 'Gintama°', 2015);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (10, 'Action, Comedy, Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1245/116760.jpg', 7, 9.05, 'Gintama: The Final', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (11, 'Action, Adventure, Fantasy', 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg', 10, 9.03, 'Hunter x Hunter (2011)', 2011);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (12, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/4/50361.jpg', 12, 9.02, 'Gintama''', 2011);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (13, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1452/123686.jpg', 13, 9.02, 'Gintama'': Enchousen', 2012);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (14, 'Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1976/142016.jpg', 11, 9.02, 'Ginga Eiyuu Densetsu', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (15, 'Action, Adventure, Fantasy', 'https://cdn.myanimelist.net/images/anime/1455/146229.jpg', 14, 9.01, 'One Piece Fan Letter', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (16, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/3/83528.jpg', 16, 8.98, 'Gintama.', 2017);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (17, 'Action, Adventure, Supernatural', 'https://cdn.myanimelist.net/images/anime/1908/135431.jpg', 15, 8.98, 'Bleach: Sennen Kessen-hen', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (18, 'Comedy, Romance', 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', 17, 8.95, 'Kaguya-sama wa Kokurasetai: Ultra Romantic', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (19, 'Drama, Romance, Supernatural', 'https://cdn.myanimelist.net/images/anime/1085/114792.jpg', 19, 8.93, 'Fruits Basket: The Final', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (20, 'Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1299/110774.jpg', 18, 8.93, 'Clannad: After Story', 2008);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (21, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 20, 8.93, 'Gintama', 2006);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (22, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg', 21, 8.93, 'Koe no Katachi', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (23, 'Award Winning, Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1088/135089.jpg', 22, 8.92, 'Code Geass: Hangyaku no Lelouch R2', 2008);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (24, 'Drama, Mystery', 'https://cdn.myanimelist.net/images/anime/1025/147458.jpg', 23, 8.91, 'Kusuriya no Hitorigoto 2nd Season', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (25, 'Drama', 'https://cdn.myanimelist.net/images/anime/3/88469.jpg', 24, 8.9, '3-gatsu no Lion 2nd Season', 2017);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (26, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/10/51723.jpg', 25, 8.89, 'Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (27, 'Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/10/18793.jpg', 26, 8.89, 'Monster', 2004);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (28, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1776/96566.jpg', 27, 8.88, 'Gintama. Shirogane no Tamashii-hen - Kouhan-sen', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (29, 'Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1921/154528.jpg', 28, 8.87, 'Sousou no Frieren 2nd Season', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (30, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1279/131078.jpg', 30, 8.86, 'Shingeki no Kyojin: The Final Season - Kanketsu-hen', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (31, 'Comedy, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/6/87322.jpg', 29, 8.86, 'Owarimonogatari 2nd Season', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (32, 'Drama, Mystery', 'https://cdn.myanimelist.net/images/anime/1708/138033.jpg', 32, 8.85, 'Kusuriya no Hitorigoto', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (33, 'Action', 'https://cdn.myanimelist.net/images/anime/1443/111830.jpg', 31, 8.85, 'Kingdom 3rd Season', 2020);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (34, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1379/145452.jpg', 33, 8.83, 'Shingeki no Kyojin Movie: Kanketsu-hen - The Last Attack', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (35, 'Action, Adventure, Drama', 'https://cdn.myanimelist.net/images/anime/1170/124312.jpg', 34, 8.83, 'Vinland Saga Season 2', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (36, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/1825/110716.jpg', 35, 8.83, 'Violet Evergarden Movie', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (37, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/5/87048.jpg', 36, 8.82, 'Kimi no Na wa.', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (38, 'Action, Comedy, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/12/89603.jpg', 37, 8.81, 'Gintama. Shirogane no Tamashii-hen', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (39, 'Drama, Sports', 'https://cdn.myanimelist.net/images/anime/3/45028.jpg', 38, 8.8, 'Ashita no Joe 2', 1980);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (40, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1000/110531.jpg', 39, 8.79, 'Shingeki no Kyojin: The Final Season', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (41, 'Action, Comedy, Supernatural', 'https://cdn.myanimelist.net/images/anime/1918/96303.jpg', 42, 8.78, 'Mob Psycho 100 II', 2019);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (42, 'Action, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/1084/112813.jpg', 41, 8.78, 'Kizumonogatari III: Reiketsu-hen', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (43, 'Action, Adventure, Drama', 'https://cdn.myanimelist.net/images/anime/1500/103005.jpg', 43, 8.78, 'Vinland Saga', 2019);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (44, 'Sports', 'https://cdn.myanimelist.net/images/anime/4/86334.jpg', 40, 8.78, 'Hajime no Ippo', 2000);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (45, 'Sports', 'https://cdn.myanimelist.net/images/anime/7/81992.jpg', 44, 8.77, 'Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou', 2016);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (46, 'Adventure, Award Winning, Fantasy', 'https://cdn.myanimelist.net/images/anime/6/79597.jpg', 45, 8.77, 'Sen to Chihiro no Kamikakushi', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (47, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1948/120625.jpg', 46, 8.77, 'Shingeki no Kyojin: The Final Season Part 2', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (48, 'Comedy, Mystery, Romance, Supernatural', 'https://cdn.myanimelist.net/images/anime/1807/121534.jpg', 47, 8.76, 'Monogatari Series: Second Season', 2013);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (49, 'Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1182/149879.jpg', 49, 8.75, 'Takopii no Genzai', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (50, 'Action, Award Winning, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/4/19644.jpg', 48, 8.75, 'Cowboy Bebop', 1998);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (51, 'Drama', 'https://cdn.myanimelist.net/images/anime/1791/154233.jpg', 50, 8.74, 'Ikoku Nikki', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (52, 'Drama', 'https://cdn.myanimelist.net/images/anime/1216/142086.jpg', 52, 8.73, 'Hibike! Euphonium 3', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (53, 'Comedy', 'https://cdn.myanimelist.net/images/anime/1448/127956.jpg', 51, 8.73, 'Bocchi the Rock!', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (54, 'Action', 'https://cdn.myanimelist.net/images/anime/1566/122794.jpg', 53, 8.73, 'Kingdom 4th Season', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (55, 'Action, Adventure, Fantasy', 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg', 54, 8.73, 'One Piece', 1999);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (56, 'Action', 'https://cdn.myanimelist.net/images/anime/1050/139641.jpg', 57, 8.72, 'Kingdom 5th Season', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (57, 'Drama', 'https://cdn.myanimelist.net/images/anime/1749/145922.jpg', 56, 8.72, 'Chi. Chikyuu no Undou ni Tsuite', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (58, 'Adventure, Mystery, Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/9/68095.jpg', 59, 8.72, 'Mushishi Zoku Shou 2nd Season', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (59, 'Action, Comedy, Supernatural', 'https://cdn.myanimelist.net/images/anime/1228/125011.jpg', 58, 8.72, 'Mob Psycho 100 III', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (60, 'Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1321/117508.jpg', 55, 8.72, '86 Part 2', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (61, 'Action', 'https://cdn.myanimelist.net/images/anime/1959/151055.jpg', 60, 8.71, 'Boku no Hero Academia: Final Season', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (62, '', 'https://cdn.myanimelist.net/images/anime/1921/135489.jpg', 0, 8.71, 'Idol', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (63, 'Comedy, Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1670/130060.jpg', 62, 8.71, 'Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (64, 'Award Winning, Drama, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/1032/135088.jpg', 61, 8.71, 'Code Geass: Hangyaku no Lelouch', 2006);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (65, 'Drama', 'https://cdn.myanimelist.net/images/anime/1979/153329.jpg', 68, 8.7, '[Oshi no Ko] 3rd Season', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (66, 'Action, Adventure, Supernatural', 'https://cdn.myanimelist.net/images/anime/1164/138058.jpg', 63, 8.7, 'Bleach: Sennen Kessen-hen - Ketsubetsu-tan', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (67, 'Drama', 'https://cdn.myanimelist.net/images/anime/1493/124765.jpg', 66, 8.7, 'Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen', 2017);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (68, 'Award Winning, Sports', 'https://cdn.myanimelist.net/images/anime/1745/129284.jpg', 67, 8.7, 'The First Slam Dunk', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (69, 'Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/1135/114867.jpg', 65, 8.7, 'Shiguang Dailiren', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (70, 'Action, Supernatural', 'https://cdn.myanimelist.net/images/anime/1792/138022.jpg', 64, 8.7, 'Jujutsu Kaisen 2nd Season', 2023);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (71, 'Fantasy', 'https://cdn.myanimelist.net/images/anime/1726/155542.jpg', 71, 8.69, 'Tongari Boushi no Atelier', 2026);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (72, 'Drama', 'https://cdn.myanimelist.net/images/anime/1795/95088.jpg', 72, 8.69, 'Violet Evergarden', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (73, 'Action, Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1656/137618.jpg', 70, 8.69, 'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (74, 'Action, Supernatural', 'https://cdn.myanimelist.net/images/anime/1908/120036.jpg', 69, 8.69, 'Kimetsu no Yaiba: Yuukaku-hen', 2022);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (75, 'Comedy, Romance', 'https://cdn.myanimelist.net/images/anime/1643/138581.jpg', 73, 8.68, 'Boku no Kokoro no Yabai Yatsu 2nd Season', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (76, 'Adventure, Mystery, Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/13/58533.jpg', 75, 8.68, 'Mushishi Zoku Shou', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (77, 'Comedy', 'https://cdn.myanimelist.net/images/anime/13/11460.jpg', 74, 8.68, 'Great Teacher Onizuka', 1999);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (78, 'Drama, Sports', 'https://cdn.myanimelist.net/images/anime/1120/152280.jpg', 82, 8.67, 'Uma Musume: Cinderella Gray Part 2', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (79, 'Action', 'https://cdn.myanimelist.net/images/anime/1282/151476.jpg', 79, 8.67, 'Kingdom 6th Season', 2025);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (80, 'Action, Adventure, Supernatural', 'https://cdn.myanimelist.net/images/anime/1595/144074.jpg', 76, 8.67, 'Bleach: Sennen Kessen-hen - Soukoku-tan', 2024);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (81, 'Action', 'https://cdn.myanimelist.net/images/anime/1492/150628.jpg', 81, 8.67, 'Tu Bian Yingxiong X', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (82, 'Sports', 'https://cdn.myanimelist.net/images/anime/8/56617.jpg', 77, 8.67, 'Hajime no Ippo: New Challenger', 2009);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (83, 'Adventure, Award Winning, Drama, Fantasy, Romance', 'https://cdn.myanimelist.net/images/anime/1470/138723.jpg', 78, 8.67, 'Howl no Ugoku Shiro', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (84, 'Action, Adventure, Award Winning, Fantasy', 'https://cdn.myanimelist.net/images/anime/1355/147277.jpg', 80, 8.67, 'Mononoke Hime', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (85, 'Action, Award Winning, Supernatural', 'https://cdn.myanimelist.net/images/anime/1681/148216.jpg', 83, 8.66, 'Kimetsu no Yaiba Movie 1: Mugenjou-hen - Akaza Sairai', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (86, 'Action, Adventure, Drama, Fantasy, Mystery', 'https://cdn.myanimelist.net/images/anime/1634/116782.jpg', 84, 8.66, 'Mo Dao Zu Shi: Wanjie Pian', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (87, 'Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1288/151853.jpg', 85, 8.65, 'Luo Xiaohei Zhanji 2', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (88, 'Adventure, Mystery, Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/2/73862.jpg', 86, 8.65, 'Mushishi', 2005);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (89, 'Action, Drama, Suspense', 'https://cdn.myanimelist.net/images/anime/1173/92110.jpg', 87, 8.65, 'Shingeki no Kyojin Season 3', 2018);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (90, 'Comedy, Mystery, Supernatural', 'https://cdn.myanimelist.net/images/anime/1142/146776.jpg', 88, 8.64, 'Monogatari Series: Off & Monster Season', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (91, 'Sports', 'https://cdn.myanimelist.net/images/anime/1427/142210.jpg', 92, 8.64, 'Uma Musume: Pretty Derby - Shin Jidai no Tobira', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (92, 'Adventure, Award Winning, Sci-Fi', 'https://cdn.myanimelist.net/images/anime/4/5123.jpg', 90, 8.64, 'Tengen Toppa Gurren Lagann', 2007);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (93, 'Drama, Romance', 'https://cdn.myanimelist.net/images/anime/1405/143284.jpg', 89, 8.64, 'Shigatsu wa Kimi no Uso', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (94, 'Action, Adventure, Drama, Fantasy', 'https://cdn.myanimelist.net/images/anime/1203/139210.jpg', 91, 8.64, 'Tian Guan Cifu Er', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (95, 'Action, Fantasy', 'https://cdn.myanimelist.net/images/anime/1142/112957.jpg', 93, 8.63, 'Fate/stay night Movie: Heaven''s Feel - III. Spring Song', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (96, 'Slice of Life, Supernatural', 'https://cdn.myanimelist.net/images/anime/3/37449.jpg', 94, 8.63, 'Natsume Yuujinchou Shi', 2012);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (97, 'Award Winning, Drama, Sports', 'https://cdn.myanimelist.net/images/anime/1586/146565.jpg', 96, 8.63, 'Ping Pong the Animation', 2014);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (98, 'Award Winning, Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/1981/113348.jpg', 95, 8.63, 'Odd Taxi', 2021);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (99, 'Drama, Mystery, Suspense', 'https://cdn.myanimelist.net/images/anime/1897/137108.jpg', 97, 8.63, 'Shiguang Dailiren II', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (100, 'Award Winning, Drama', 'https://cdn.myanimelist.net/images/anime/1716/142633.jpg', 102, 8.62, 'Look Back', NULL);
INSERT INTO public.anime (id, genre, image_url, rank, score, title, year) VALUES (101, 'Action, Supernatural', 'https://cdn.myanimelist.net/images/anime/1659/154920.jpg', 101, 8.62, 'Jujutsu Kaisen: Shimetsu Kaiyuu - Zenpen', 2026);


--
-- Name: anime_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.anime_id_seq', 101, true);


--
-- Name: anime anime_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anime
    ADD CONSTRAINT anime_pkey PRIMARY KEY (id);


--
-- Name: anime uk54eaowtdrykgn24dd0g93dcy4; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.anime
    ADD CONSTRAINT uk54eaowtdrykgn24dd0g93dcy4 UNIQUE (title);


--
-- PostgreSQL database dump complete
--

\unrestrict HyQftaH4Ns31BXAoePWiqkVv0T6Ma1AsVNpcsKypXiKJRA5hoJHvr3wENXIxvae

